server.port=8765
spring.datasource.url=jdbc:sqlite:data/financas.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.web.resources.static-locations=classpath:/static/,file:./static/
spring.mvc.static-path-pattern=/**
